### ISSUE TITLE
[bug] Invalid memory access error

### ISSUE THREAD

**Issue by AoDev** [clns/node-commit-msg#1]
When this happens: _when the message is valid_.
If invalid, it does not reach that point.

The error I get:

```
Invalid memory access of location 0x0 rip=0x105e9d866
error: .git/hooks/commit-msg died of signal 11
```

Running with iojs 1.7.1

Config is the angular guidelines from examples in this repo.

**Comment by clns** [comment]
I'm unable to replicate the issue. Please provide the commit message that is failing.

Alternatively [this docker image](https://hub.docker.com/r/clns/commit-msg-issue1/) replicates your setup with io.js v1.7.1 and the angular guidelines config. You can follow its usage to get it working and try the commit message yourself.

**Comment by AoDev** [comment]
This was the message I tried to commit (I just tried and failed again on my machine)

```
 git commit -m "feat(service): getById includes processTimeSla"
```

in the docker container you provided, it does continue, but, with another error:

```
error (1,16): Use imperative present tense, eg. "Fix bug" not "Fixed bug" or "Fixes bug". To get it right ask yourself: "If applied, this patch will <YOUR-COMMIT-MESSAGE-HERE>"
```

I don't get this error on my machine, but the memory error message.

Then, if I correct the message to :

```
git commit -m "feat(service): include processTimeSla in getById"
```

It works in the docker container. But, this still fails in my machine, with the same memory error.
I thought, maybe some problem with pre-commit hook. But disabling it did not change anything.

Hum, I'll try to get someone I know to try.

**Comment by clns** [comment]
The behavior in the docker image is correct. The "_getById includes processTimeSla_" sentence is detected as present tense 3rd person singular, so it throws an error. The corrected sentence is in imperative mode so it should pass, which it does.

The memory access error looks like it's specific to your machine/configuration. Unfortunately I cannot help you more with this without being able to replicate the same error.

Do you have node-java installed? It's possible you have a problem with that. You could try without it by simply uninstalling it with `npm uninstall java` from your project root. This will force the validator to use the java cli command instead of the java API directly, which is perfectly fine if you don't do [bulk validations](https://github.com/clns/node-commit-msg/blob/master/CONTRIBUTING.md#2-install-the-optional-prerequisites).

**Comment by AoDev** [comment]
I understand. I haven't tried what you said about java yet.
I'll investigate a bit more and let you know.
I am running on OSX 10.9 Maverick

**Comment by clns** [comment]
I'll go ahead and close this issue, feel free to re-open it if you need to.
